version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    environment:
    - PROVAR_HOME: ProvarLibs
    - testproject.home: TestProject
    - testproject.results: TestProject/Results
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - run: echo $PROVAR_HOME
    - run: ant -lib $PROVAR_HOME/ant -f TestProject/ANT/build.xml
workflows:
  version: 2
  workflow:
    jobs:
    - build
