# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-browsers
      #- image: circleci/node-jessie-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

   # working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      PROVAR_HOME: ProvarLibs
      testproject.home: TestProject
      testproject.results: TestProject/Results
    
    steps:
      - checkout
    

      # Download and cache dependencies
     # - restore_cache:
          #keys:
          #- v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          #- v1-dependencies-
     # - run: sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
     # - run: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
     # - run: sudo apt-get update
     #- run: sudo apt-get install -y google-chrome-stable
     # - run: sudo apt-get install -y xvfb
      - run: echo $PROVAR_HOME
      - run: echo $testproject.home
      - run: cp -rf /home/circleci/project/TestProject/.smtp /home/circleci/Provar/
      - run: ant -lib $PROVAR_HOME/ant -f TestProject/ANT/build.xml
      - store_artifacts:
          path: /home/circleci/project/TestProject/Results
          destination: Test_Run_Report.pdf
      - store_artifacts:
          path: /home/circleci/project/TestProject/Results
        
